### ISSUE TITLE
LNK2001: unresolved external symbol mainCRTStartup

### ISSUE THREAD

**Issue by JohnKServices** [ShiftMediaProject/VSNASM#7]
Hello, I have set everything up and manually installed it. I made a new empty C++ project and deleted all the folders and set it to `Build customization` NASM, and went to the `.asm` file's properties and set it to Netwide Assembler, but with 
```nasm
section .data

section .text
global main

main:
	mov eax, 5
``` 
to test if it works I get the error as in the title (`LNK2001: unresolved external symbol mainCRTStartup`). If you need any more info or have any idea how to fix it, please let me know!

**Comment by Sibras** [comment]
Thats an issue with the msvc linker expecting code that conforms to the windows C run-time (CRT) standards. The CRT has a function called mainCRTStartup that intialises the CRT and then calls the user main function.

So your issue is that your using the C linker but your project doesnt have any C/C++ source files in it so its not properly linking in the CRT libraries.

Either just create your main function in a C file and use NASM for other specific functions only or youll need to fix up the missing linker elements.

For more on CRT see:
[https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx?f=255&MSPPError=-2147217396](https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx?f=255&MSPPError=-2147217396)
